version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: saudenow-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Opcional: Redis UI para visualizar dados
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: saudenow-redis-ui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data: