# Railway Monorepo Configuration
# Deploy both middleware-api and workers services

[environments.production.services.middleware-api]
build.builder = "DOCKERFILE"
build.dockerfilePath = "Dockerfile.middleware-api"
build.watchPaths = [
  "packages/middleware-api/**",
  "Dockerfile.middleware-api"
]
deploy.healthcheckPath = "/api/health"
deploy.healthcheckTimeout = 300

[environments.production.services.workers]
build.builder = "DOCKERFILE"
build.dockerfilePath = "Dockerfile.workers"
build.watchPaths = [
  "packages/workers/**",
  "Dockerfile.workers"
]
deploy.healthcheckPath = "/health"
deploy.healthcheckTimeout = 300