[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.middleware-api"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

[healthcheck]
httpPath = "/api/health"
initialDelaySeconds = 30
periodSeconds = 10
timeoutSeconds = 5
failureThreshold = 3
successThreshold = 1